# Generated by Django 6.0.7 on 2026-08-21 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='downloads_count',
        ),
        migrations.AddField(
            model_name='book',
            name='downloaded_by',
            field=models.ManyToManyField(blank=True, related_name='downloaded_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
