# Generated by Django 6.0.7 on 2026-08-24 22:01

from django.db import migrations


def create_initial_genres(apps, schema_editor):
    # Метод apps.get_model гарантирует, что мы используем правильную
    # версию модели Genre именно на момент применения этой миграции
    Genre = apps.get_model('books', 'Genre')
    genres = ['Программирование', 'Базы данных', 'Математика', 'Дизайн', 'Веб-разработка', 'Сети']

    for genre_name in genres:
        Genre.objects.get_or_create(name=genre_name)

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_downloads_count_book_downloaded_by'),
    ]

    operations = [
        migrations.RunPython(create_initial_genres),
    ]
